//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikutku.Constants {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ikutku.Constants.StringsResource", typeof(StringsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your ikutku account has been synched..
        /// </summary>
        public static string ACC_READY_MSG {
            get {
                return ResourceManager.GetString("ACC_READY_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have reset your account due to problems authenticating with twitter. Please sign in again..
        /// </summary>
        public static string ACC_RESET_AUTH_MESSAGE {
            get {
                return ResourceManager.GetString("ACC_RESET_AUTH_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have reset your account as you have not signed in for awhile. You will need to login again..
        /// </summary>
        public static string ACC_RESET_STALE_MESSAGE {
            get {
                return ResourceManager.GetString("ACC_RESET_STALE_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update in progress.
        /// </summary>
        public static string DB_SYNCING {
            get {
                return ResourceManager.GetString("DB_SYNCING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to processing.
        /// </summary>
        public static string QUEUE_PROCESSING {
            get {
                return ResourceManager.GetString("QUEUE_PROCESSING", resourceCulture);
            }
        }
    }
}
