//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikutku.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class cachedUser
    {
        public cachedUser()
        {
            this.followers = new HashSet<follower>();
            this.followings = new HashSet<following>();
        }
    
        public long id { get; set; }
        public string twitterid { get; set; }
        public string screenName { get; set; }
        public string profileImageUrl { get; set; }
        public decimal ratio { get; set; }
        public Nullable<System.DateTime> lastTweet { get; set; }
        public System.DateTime updated { get; set; }
        public int followingsCount { get; set; }
        public int followersCount { get; set; }
    
        public virtual ICollection<follower> followers { get; set; }
        public virtual ICollection<following> followings { get; set; }
    }
}
