//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikutku.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ikutkuEntities : DbContext
    {
        public ikutkuEntities()
            : base("name=ikutkuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<loginInterval> loginIntervals { get; set; }
        public DbSet<queuedUser> queuedUsers { get; set; }
        public DbSet<queueTime> queueTimes { get; set; }
        public DbSet<statistic> statistics { get; set; }
        public DbSet<usersInList> usersInLists { get; set; }
        public DbSet<usersList> usersLists { get; set; }
        public DbSet<queuedFollowingUser> queuedFollowingUsers { get; set; }
        public DbSet<cachedUser> cachedUsers { get; set; }
        public DbSet<errorCounter> errorCounters { get; set; }
        public DbSet<follower> followers { get; set; }
        public DbSet<following> followings { get; set; }
        public DbSet<user> users { get; set; }
    }
}
