//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ikutku.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class queuedUser
    {
        public long id { get; set; }
        public string ownerid { get; set; }
        public int settings { get; set; }
    
        public virtual user user { get; set; }
    }
}
